### ISSUE TITLE
Application hangs on quit in windows standalone, if NativeInterface.StartScan has been called

### ISSUE THREAD

**Issue by marko-kr1** [GameWithPixels/PixelsUnityPlugin#3]
On Windows Standalone, the application hangs when quitting. 
It happens when the following methods are invoked:

- `NativeInterface.Initialize();`
- `NativeInterface.StartScan(<arguments...>);`

The problem occurs even if `StopScan()` and `Shutdown()` are called after the fact and no native handles are created at any point.
This is very apparent in built applications as it happens when exiting the app. It's less apparent in the editor, as it doesn't happen when the game is stopped, only when exiting the editor itself.

**Comment by obasille** [comment]
Yes this is a known issue (or limitation) with Unity. When a thread from a native plugin calls back some C# code, Unity will thinks it owns the thread and wait on it to terminate before shutting down.

I believe this only happens for threads created by WinRT though (the plugin uses WinRT to access BLE).

I can think of 2 way to get around that issue:
1. Manually track threads that callback Unity code and kill them on shutdown (that might cause a crash though)
2. Re-factor the plugin code to store events in a queue rather than directly invoke the C# callback, and then have the Unity code poll for queued events on each render update

I'm only using this plugin for building mobile app so I never took the time to address this issue. Also I was kind of hoping that Unity would eventually fix this issue at some point.

**Comment by obasille** [comment]
I should add that those thread are created by WinRT, not by the plugin itself.

Also a third option would be to transfer the C# callback invocation to another thread inside the plugin. This thread would need to be "purely" native (not created by WinRT) or created by Unity.

**Comment by marko-kr1** [comment]
Don't the callback threads from the plugin terminate when the callback completes? If not, would it be possible to terminate them from within the plugin when shutdown is called?

**Comment by obasille** [comment]
No those threads are created and managed by the WinRT APIs (not the plugin itself). I imagine that they are kept in a pool to avoid creating new threads all the time.

Either Unity code or the plugin code could track those threads and kill them on shutdown, that might cause a crash as WinRT might still be doing some work with them.

**Comment by marko-kr1** [comment]
Ty for all the info. I'll try killing them off in Unity as a first step. It seems like the easiest to implement.
Edit: apparently aborting threads is no longer a thing since .NET 5
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/thread-abort-obsolete

**Comment by mark-kray** [comment]
This problem no longer occurs on the 2022LTS version. So the issue can be closed

**Comment by obasille** [comment]
Thanks for letting us know!
